# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lCe8d_2z4SBZ19amkGLlDfgbWgvLSsJN
"""

"""
src/predict.py
Inference Engine for EndpointShield AI

Loads serialized static model artifacts and runs static malware binary predictions.
"""

import argparse
import os
import sys
import joblib
import numpy as np
import pandas as pd
from Dataset_preprocessing import clean_and_split_features

MODEL_PATH = "data/processed/baseline_model.pkl"


def load_model(model_path: str = MODEL_PATH):
    """Loads trained model artifact from disk."""
    if not os.path.exists(model_path):
        print(f"[-] Warning: Model file not found at {model_path}.")
        print("[!] Train model using notebooks/Baseline_Model.ipynb first.")
        return None

    print(f"[+] Loading model artifact from {model_path}...")
    model = joblib.load(model_path)
    return model


def predict(input_csv_path: str, threshold: float = 0.5):
    """
    Executes static binary classification pipeline on input CSV feature matrix.
    Returns DataFrame with probabilities and binary decision labels.
    """
    if not os.path.exists(input_csv_path):
        raise FileNotFoundError(f"[-] Input CSV not found at: {input_csv_path}")

    # 1. Ingest Raw Input Data
    raw_df = pd.read_csv(input_csv_path)

    # 2. Preprocess & Clean Matrix
    X, _ = clean_and_split_features(raw_df)

    # 3. Load Trained Artifact
    model = load_model()

    df_results = raw_df.copy()

    if model is not None:
        # Generate prediction probabilities
        if hasattr(model, "predict_proba"):
            probs = model.predict_proba(X)[:, 1]
        else:
            probs = model.predict(X)

        predictions = (probs >= threshold).astype(int)
        df_results["Threat_Probability"] = probs
        df_results["Prediction_Label"] = np.where(
            predictions == 1, "MALICIOUS", "BENIGN"
        )
    else:
        # Fallback dummy execution for pipeline validation before training
        print("[!] Executing pipeline in fallback dry-run mode...")
        df_results["Threat_Probability"] = 0.0000
        df_results["Prediction_Label"] = "UNKNOWN (MODEL MISSING)"

    print("\n=== EndpointShield AI — Sample Static Malware Scans ===")
    print(df_results[["Prediction_Label", "Threat_Probability"]].head(10))

    return df_results


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="EndpointShield AI Static Malware Inference Engine"
    )
    parser.add_argument(
        "--input",
        type=str,
        default="data/raw/sample.csv",
        help="Path to feature vector CSV file",
    )
    parser.add_argument(
        "--threshold",
        type=float,
        default=0.5,
        help="Decision probability threshold for malware recall tuning",
    )
    args = parser.parse_args()

    predict(input_csv_path=args.input, threshold=args.threshold)