# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lCe8d_2z4SBZ19amkGLlDfgbWgvLSsJN
"""

"""
src/sanity_check.py
Pipeline Validation & Environment Verification Script
"""

import os
import sys
import pandas as pd


def verify_environment():
    """Verifies repository architecture and data schema integrity."""
    print("=== EndpointShield AI — Sanity & Integrity Check ===\n")

    # 1. Check directory tree structure
    required_dirs = ["data/raw", "data/processed", "notebooks", "src", "dashboard"]
    for d in required_dirs:
        if os.path.exists(d):
            print(f"[✓] Directory exists: {d}")
        else:
            print(f"[✗] MISSING DIRECTORY: {d}")

    # 2. Validate sample dataset presence & shape
    sample_path = "data/raw/sample.csv"
    if os.path.exists(sample_path):
        df = pd.read_csv(sample_path)
        print(f"\n[✓] Sample dataset found at: {sample_path}")
        print(
            f"    - Dimensions: {df.shape[0]} rows x {df.shape[1]} columns"
        )
        if "label" in df.columns:
            print(
                f"    - Class Labels Present: {df['label'].unique().tolist()}"
            )
        else:
            print("    - [!] Warning: 'label' column missing from sample.csv")
    else:
        print(
            f"\n[✗] MISSING FILE: {sample_path} (Waiting for Noel to push sample.csv)"
        )

    print("\n=== Verification Complete ===")


if __name__ == "__main__":
    verify_environment()